"""Stage 5/7 publish: write the daily Markdown digest for GitHub Pages.



The English edition (posts/YYYY-MM-DD-techtally.md) is canonical; for every

extra language configured in sources.yaml a sibling file

(posts/YYYY-MM-DD-techtally-<code>.md) is rendered from the stored

translations, preserving the English author's voice. Localized labels and

native language names come from config/i18n.yaml (UTF-8 data); unknown

languages fall back to the English labels and text.



Every edition carries full author attribution (front-matter author +

description, visible byline, footer links) and a language switcher line, so

readers - and search engines - can move between the editions of one day.

"""



from __future__ import annotations



import logging

import re

from datetime import date

from pathlib import Path



import yaml



from src.models import CuratedItem, utc_now



logger = logging.getLogger(__name__)





# Built-in English labels: the baseline every i18n block overrides from.

# Placeholders: __DATE__/__NAME__ in meta_description + meta_by,

# __N__/__S__/__NWORD__/__SWORD__ in intro, __REPO__/__STAMP__ in generated.

# __NWORD__/__SWORD__ resolve to the story_one/story_many and

# source_one/source_many forms of the same language.

_EN_DEFAULTS = {

    "native_name": "English",

    "dir": "ltr",

    "og_locale": "en_US",

    "meta_description": (

        "TechTally daily digest for __DATE__: the day's top tech stories "

        "summarized with expert commentary"

    ),

    "meta_by": ", curated by __NAME__.",

    "intro": (

        "__N__ __NWORD__ from __S__ __SWORD__, ranked by coverage, "

        "community signal, and recency."

    ),

    "read_in": "Read this digest in",

    "curated_by": "Curated by",

    "footer_by": "Curated by:",

    "generated": "Auto-generated by __REPO__ on __STAMP__.",

    "source": "Source",

    "topic": "Topic",

    "coverage": "Coverage",

    "source_one": "source",

    "source_many": "sources",

    "story_one": "story",

    "story_many": "stories",

    "discuss": "Discussion",

    "summary_h": "Summary",

    "take_h": "My Take",

}





def load_i18n(path: Path | str) -> dict:

    """Read config/i18n.yaml (UTF-8); missing file means English everywhere."""



    path = Path(path)



    if not path.exists():

        logger.warning(

            "i18n file not found: %s - using English labels",

            path,

        )

        return {}



    with open(path, encoding="utf-8") as stream:

        return yaml.safe_load(stream) or {}





def _labels(lang: str, i18n: dict | None) -> dict:

    """Merge label sources: built-in defaults <- i18n['en'] <- i18n[lang]."""



    merged = dict(_EN_DEFAULTS)



    for block in (

        (i18n or {}).get("en"),

        (i18n or {}).get(lang),

    ):

        if isinstance(block, dict):

            merged.update(

                {

                    key: str(value)

                    for key, value in block.items()

                }

            )



    return merged





def _edition_filename(

    day: date,

    lang: str,

    extension: str = "md",

    posts_dir=None,

) -> str:

    """File name of one edition: en has no suffix, others get -<code>.



    Slug history: editions written before the TechTally rebrand use the

    legacy -tech-digest slug and those files stay untouched on disk.

    When posts_dir is given, the slug family that actually exists for the

    day wins, so backfill re-renders of legacy days keep every sibling

    and switcher link pointing at the real files. A language with no file

    yet follows the day's English edition family, so one day never mixes

    slug families.

    """



    suffix = "" if lang == "en" else f"-{lang}"



    if posts_dir is not None:

        posts_path = Path(posts_dir)



        for base in ("techtally", "tech-digest"):

            if (

                posts_path

                / f"{day.isoformat()}-{base}{suffix}.md"

            ).exists():

                return (

                    f"{day.isoformat()}-{base}"

                    f"{suffix}.{extension}"

                )



        if lang != "en":

            for base in ("techtally", "tech-digest"):

                if (

                    posts_path

                    / f"{day.isoformat()}-{base}.md"

                ).exists():

                    return (

                        f"{day.isoformat()}-{base}"

                        f"{suffix}.{extension}"

                    )



    return f"{day.isoformat()}-techtally{suffix}.{extension}"





def existing_editions(

    posts_dir: Path | str,

    day: date | None = None,

) -> list[Path]:

    """Digest files already on disk for the given day, across all editions."""



    day = day or utc_now().date()

    posts_path = Path(posts_dir)



    if not posts_path.is_dir():

        return []



    return sorted(

        set(

            posts_path.glob(

                f"{day.isoformat()}-techtally*.md"

            )

        )

        | set(

            posts_path.glob(

                f"{day.isoformat()}-tech-digest*.md"

            )

        )

    )





def _has_complete_translation(

    item: CuratedItem,

    language: str,

) -> bool:

    """Return whether an item has all required translated fields."""



    translation = (

        item.translations or {}

    ).get(language)



    if not isinstance(translation, dict):

        return False



    return all(

        isinstance(translation.get(field), str)

        and translation[field].strip()

        for field in (

            "title",

            "summary",

            "take",

        )

    )





def _published_languages(

    items: list[CuratedItem],

    languages: list[str],

) -> list[str]:

    """Return languages with complete translations for every item."""



    published: list[str] = []



    for language in dict.fromkeys(languages):

        language = str(language).strip().lower()



        if not language or language == "en":

            continue



        if all(

            _has_complete_translation(

                item,

                language,

            )

            for item in items

        ):

            published.append(language)



    return published





def write_digest(

    items: list[CuratedItem],

    day: date | None = None,

    posts_dir: Path | str = "posts",

    author: dict | None = None,

    languages: list[str] | None = None,

    i18n: dict | None = None,

) -> Path:

    """Write the English edition plus every fully translated sibling.



    A translated edition is written only when every selected article has

    complete values for title, summary, and take in that language. This

    prevents partially translated pages from silently falling back to

    English content.

    """



    if not items:

        raise ValueError("no curated items to publish")



    day = day or utc_now().date()

    posts_path = Path(posts_dir)

    posts_path.mkdir(

        parents=True,

        exist_ok=True,

    )



    extra_languages = [

        str(code).strip().lower()

        for code in dict.fromkeys(languages or [])

        if str(code).strip()

        and str(code).strip().lower() != "en"

    ]



    i18n = i18n or {}



    # Only fully translated languages are published.

    published_languages = _published_languages(

        items,

        extra_languages,

    )



    skipped_languages = [

        language

        for language in extra_languages

        if language not in published_languages

    ]



    canonical = (

        posts_path

        / _edition_filename(

            day,

            "en",

            posts_dir=posts_path,

        )

    )



    canonical.write_text(

        _render(

            items,

            day,

            author,

            "en",

            i18n,

            published_languages,

            posts_path.name,

            posts_dir=posts_path,

        ),

        encoding="utf-8",

    )



    logger.info(

        "digest written: %s (%d items)",

        canonical,

        len(items),

    )



    for language in skipped_languages:

        translated_count = sum(

            _has_complete_translation(

                item,

                language,

            )

            for item in items

        )



        logger.warning(

            "translated digest skipped for %s: "

            "incomplete translation (%d/%d items)",

            language,

            translated_count,

            len(items),

        )



    for language in published_languages:

        path = (

            posts_path

            / _edition_filename(

                day,

                language,

                posts_dir=posts_path,

            )

        )



        path.write_text(

            _render(

                items,

                day,

                author,

                language,

                i18n,

                published_languages,

                posts_path.name,

                posts_dir=posts_path,

            ),

            encoding="utf-8",

        )



        logger.info(

            "translated digest written: %s",

            path,

        )



    if published_languages:

        logger.info(

            "editions: %d languages (%s); skipped=%s",

            1 + len(published_languages),

            ", ".join(

                ["en"] + published_languages

            ),

            ", ".join(

                skipped_languages

            ) or "none",

        )

    else:

        logger.info(

            "editions: English only; "

            "skipped=%s",

            ", ".join(

                skipped_languages

            ) or "none",

        )



    return canonical





def _render(

    items: list[CuratedItem],

    day: date,

    author: dict | None,

    lang: str,

    i18n: dict,

    languages: list[str],

    dir_name: str,

    posts_dir: Path | str | None = None,

    with_front_matter: bool = True,

) -> str:

    """Full document for one language: front-matter, header, items, footer."""



    t = _labels(

        lang,

        i18n,

    )



    sources = sorted(

        {

            item.article.source

            for item in items

        }

    )



    header = _header(

        items,

        day,

        sources,

        author,

        lang,

        t,

        i18n,

        languages,

        dir_name,

        with_front_matter,

        posts_dir=posts_dir,

    )



    blocks = [

        _item_block(

            index,

            item,

            lang,

            t,

        )

        for index, item in enumerate(

            items,

            1,

        )

    ]



    return (

        header

        + "\n---\n\n".join(blocks)

        + "\n"

        + _footer(

            author,

            t,

        )

    )





def _header(

    items: list[CuratedItem],

    day: date,

    sources: list[str],

    author: dict | None,

    lang: str,

    t: dict,

    i18n: dict,

    languages: list[str],

    dir_name: str,

    with_front_matter: bool = True,

    posts_dir: Path | str | None = None,

) -> str:

    """YAML front-matter plus H1, byline, and language switcher."""



    name = (

        (author or {}).get("name")

        or ""

    )



    linkedin = (

        (author or {}).get("linkedin")

        or ""

    )



    title = (

        f"TechTally - {day.isoformat()}"

        + (

            f" | {name}"

            if name

            else ""

        )

    )



    description = (

        t["meta_description"]

        .replace(

            "__DATE__",

            day.isoformat(),

        )

        + (

            t["meta_by"].replace(

                "__NAME__",

                name,

            )

            if name

            else "."

        )

    )



    author_line = (

        f'author: "{name}"\n'

        if name

        else ""

    )



    cover = next(

        (

            item.article.image_url

            for item in items

            if item.article.image_url

        ),

        None,

    )



    cover_line = (

        f'cover: "{cover}"\n'

        if cover

        else ""

    )



    sword = (

        t["source_one"]

        if len(sources) == 1

        else t["source_many"]

    )



    nword = (

        t["story_one"]

        if len(items) == 1

        else t["story_many"]

    )



    intro = (

        t["intro"]

        .replace(

            "__N__",

            str(len(items)),

        )

        .replace(

            "__S__",

            str(len(sources)),

        )

        .replace(

            "__SWORD__",

            sword,

        )

        .replace(

            "__NWORD__",

            nword,

        )

    )



    front_matter = ""



    if with_front_matter:

        front_matter = (

            "---\n"

            f'title: "{title}"\n'

            f"date: {day.isoformat()}\n"

            f"items: {len(items)}\n"

            f"sources: [{', '.join(sources)}]\n"

            f"{cover_line}"

            f"lang: {lang}\n"

            f"dir: {t['dir']}\n"

            f"og_locale: {t['og_locale']}\n"

            f"{_translations_front_matter(day, lang, languages, i18n, dir_name, posts_dir)}"

            f"{author_line}"

            f'description: "{description}"\n'

            "generator: techtally\n"

            "---\n\n"

        )



    return (

        front_matter

        + f"# TechTally - {day.isoformat()}\n\n"

        + f"_{intro}_\n\n"

        + _byline(

            name,

            linkedin,

            t,

        )

        + _switcher(

            day,

            lang,

            languages,

            i18n,

            posts_dir,

        )

    )





def _translations_front_matter(
    day: date,
    lang: str,
    languages: list[str],
    i18n: dict,
    dir_name: str,
    posts_dir: Path | str | None = None,
) -> str:
    """On the English edition only: sibling files that actually exist."""

    if lang != "en" or not languages:
        return ""

    lines = ["translations:"]
    posts_path = Path(posts_dir) if posts_dir is not None else None

    for code in languages:
        code = str(code).strip().lower()

        if not code or code == "en":
            continue

        filename = _edition_filename(
            day,
            code,
            "html",
            posts_dir,
        )

        if posts_path is None or not (posts_path / filename).exists():
            continue

        native = _labels(code, i18n)["native_name"]
        file_url = f"{dir_name}/{filename}"

        lines.append(
            f'  - {{code: {code}, name: "{native}", '
            f'file: "{file_url}"}}'
        )

    if len(lines) == 1:
        return ""

    return "\n".join(lines) + "\n"


def _switcher(
    day: date,
    lang: str,
    languages: list[str],
    i18n: dict,
    posts_dir: Path | str | None = None,
) -> str:
    """Show every configured language and link only to editions that exist."""

    codes = [
        "en",
        *[
            str(code).strip().lower()
            for code in languages
            if str(code).strip().lower() != "en"
        ],
    ]

    codes = list(dict.fromkeys(codes))
    links: list[str] = []
    posts_path = Path(posts_dir) if posts_dir is not None else None

    for code in codes:
        if code == lang:
            continue

        native = _labels(code, i18n)["native_name"]
        filename = _edition_filename(
            day,
            code,
            "html",
            posts_dir,
        )

        exists = (
            posts_path is not None
            and (posts_path / filename).exists()
        )

        if exists:
            links.append(
                f'<a class="lang-pill" '
                f'href="{filename}">{native}</a>'
            )
        else:
            links.append(
                f'<span class="lang-pill lang-pill-disabled" '
                f'aria-disabled="true">{native}</span>'
            )

    if not links:
        return ""

    read_in = _labels(lang, i18n)["read_in"]

    return (
        f"**{read_in}:** "
        + " ".join(links)
        + "\n\n"
    )


def _byline(

    name: str,

    linkedin: str,

    t: dict,

) -> str:

    """Visible curator line near the top of the page."""



    if not name:

        return ""



    if linkedin:

        return (

            f"_{t['curated_by']} "

            f"[{name}]({linkedin})_\n\n"

        )



    return (

        f"_{t['curated_by']} "

        f"{name}_\n\n"

    )





def _item_block(

    index: int,

    item: CuratedItem,

    lang: str,

    t: dict,

) -> str:

    """Render one numbered story."""



    article = item.article



    if lang == "en":

        title = article.title

        summary = item.llm_summary

        take = item.personal_take

    else:

        # write_digest() guarantees that a published language has a

        # complete translation for every item. Keep this guard here as

        # defense-in-depth in case _render() is called directly.

        if not _has_complete_translation(

            item,

            lang,

        ):

            raise ValueError(

                f"incomplete {lang} translation "

                f"for article {index}"

            )



        translation = (

            item.translations or {}

        ).get(lang)



        title = translation["title"]

        summary = translation["summary"]

        take = translation["take"]



    topic = article.meta.get(

        "category",

        "general",

    )



    coverage = article.meta.get(

        "coverage",

        1,

    )



    coverage_word = (

        t["source_one"]

        if coverage == 1

        else t["source_many"]

    )



    # Reader-friendly escape hatch for login-walled story URLs and a

    # general link to the community thread.

    discussion = str(

        article.meta.get(

            "discussion_url"

        )

        or ""

    )



    discuss_link = ""



    if (

        discussion

        and discussion.rstrip("/")

        != article.url.rstrip("/")

    ):

        discuss_link = (

            f"  |  "

            f"[{t['discuss']}]"

            f"({discussion})"

        )



    parts = [

        (

            f"## {index}. "

            f"[{title}]({article.url})\n\n"

        ),

        _image_markdown(

            article,

            title,

        ),

        (

            f"**{t['source']}:** "

            f"{article.source}  |  "

            f"**{t['topic']}:** "

            f"{topic}  |  "

            f"**{t['coverage']}:** "

            f"{coverage} {coverage_word}"

            f"{discuss_link}\n\n"

        ),

        f"**{t['summary_h']}**\n\n",

        f"{summary}\n\n",

        f"**{t['take_h']}**\n\n",

        f"{_blockquote(take)}\n",

    ]



    return "".join(parts)





def _image_markdown(

    article,

    alt_title: str | None = None,

) -> str:

    """Markdown image for the story lead."""



    url = article.image_url



    if not url:

        return ""



    alt = _safe_alt(

        alt_title or article.title

    )



    destination = _safe_destination(

        url

    )



    return (

        f"![{alt}]({destination})\n\n"

    )





def _safe_alt(

    title: str,

) -> str:

    """Keep the title from breaking the image alt-text brackets."""



    return (

        title

        .replace("[", "(")

        .replace("]", ")")

        .replace('"', "'")

    )





def _safe_destination(

    url: str,

) -> str:

    """Escape spaces and parenthesized paths in Markdown URLs."""



    url = url.replace(

        " ",

        "%20",

    )



    if "(" in url or ")" in url:

        url = f"<{url}>"



    return url





def _blockquote(

    text: str,

) -> str:

    """Render the take as a Markdown blockquote."""



    return "\n".join(

        f"> {line}".rstrip()

        for line in text.splitlines()

    )





def _footer(

    author: dict | None,

    t: dict,

) -> str:

    """Generation stamp plus curator attribution."""



    author = author or {}



    stamp = utc_now().strftime(

        "%Y-%m-%d %H:%M UTC"

    )



    repo = author.get(

        "repository"

    ) or ""



    repo_link = (

        f"[TechTally]({repo})"

        if repo

        else "[TechTally]"

    )



    generated = (

        t["generated"]

        .replace(

            "__REPO__",

            repo_link,

        )

        .replace(

            "__STAMP__",

            stamp,

        )

    )



    lines = [

        f"*{generated}*"

    ]



    name = author.get("name")



    if name:

        profile_links = " | ".join(

            f"[{label}]({author[key]})"

            for label, key in (

                ("LinkedIn", "linkedin"),

                ("GitHub", "github"),

            )

            if author.get(key)

        )



        attribution = (

            f"**{name}**"

            + (

                f" | {profile_links}"

                if profile_links

                else ""

            )

        )



        lines.append(

            f"{t['footer_by']} "

            f"{attribution}"

        )



    return (

        "---\n\n"

        + "\n\n".join(lines)

        + "\n"

    )





# --- Home-page include (stage 5c) -------------------------------------------



# The home page shows the newest English edition INLINE.

# Jekyll cannot reliably render one page's Markdown inside another page, so

# the pipeline converts the edition itself and drops it into

# _includes/latest_digest.html (+ _data/latest_digest.yml).



_HREF_RE = re.compile(

    r'href="(?!https?://|#|/|data:|mailto:)([^"]+)"'

)





def read_baseurl(

    config_yml: Path | str,

    repository: str = "",

) -> str:

    """Best-effort site baseurl for the homepage include."""



    try:

        with open(

            config_yml,

            encoding="utf-8",

        ) as stream:

            data = yaml.safe_load(

                stream

            ) or {}



        explicit = str(

            data.get("baseurl")

            or ""

        ).rstrip("/")



        if explicit:

            return explicit



    except OSError:

        pass



    match = re.search(

        r"github\\.com/[^/]+/([^/?#]+)/?$",

        (repository or "").rstrip("/"),

    )



    if match:

        name = match.group(1)



        return (

            ""

            if name.endswith(".github.io")

            else f"/{name}"

        )



    return ""





def _markdown_to_html(

    text: str,

) -> str | None:

    """Convert Markdown to HTML when python-markdown is available."""



    try:

        import markdown

    except ImportError:

        logger.warning(

            "package 'markdown' not installed - "

            "latest-digest include skipped"

        )

        return None



    return markdown.markdown(

        text

    )





def write_latest_include(

    items: list[CuratedItem],

    day: date,

    author: dict | None,

    i18n: dict,

    languages: list[str],

    dir_name: str,

    baseurl: str,

    include_dir: Path | str,

    data_dir: Path | str,

    posts_dir: Path | str | None = None,

) -> Path | None:

    """Write _includes/latest_digest.html + _data/latest_digest.yml."""



    # The homepage include is English only, but the switcher must still

    # reference only translated editions that actually exist.

    published_languages = _published_languages(

        items,

        languages,

    )



    body = _render(

        items,

        day,

        author,

        "en",

        i18n,

        published_languages,

        dir_name,

        posts_dir=posts_dir,

        with_front_matter=False,

    )



    html = _markdown_to_html(

        body

    )



    if html is None:

        return None



    prefix = (

        (baseurl or "").rstrip("/")

        + f"/{dir_name.strip('/')}/"

    )



    html = _HREF_RE.sub(

        lambda match: (

            f'href="{prefix}'

            f'{match.group(1)}"'

        ),

        html,

    )



    # Offscreen publisher images must not block the homepage render.

    html = html.replace(

        "<img ",

        '<img loading="lazy" decoding="async" ',

    )



    stamp = utc_now().strftime(

        "%Y-%m-%d %H:%M UTC"

    )



    include_path = (

        Path(include_dir)

        / "latest_digest.html"

    )



    include_path.parent.mkdir(

        parents=True,

        exist_ok=True,

    )



    include_path.write_text(

        '<article class="digest" '

        'lang="en" dir="ltr">\n'

        f"<!-- generated by techtally on "

        f"{stamp}; regenerated on every publish -->\n"

        f"{html}\n"

        "</article>\n",

        encoding="utf-8",

    )



    data_path = (

        Path(data_dir)

        / "latest_digest.yml"

    )



    data_path.parent.mkdir(

        parents=True,

        exist_ok=True,

    )



    data_path.write_text(

        f'date: "{day.isoformat()}"\n'

        f'file: "{dir_name.strip("/")}/'

        f'{_edition_filename(day, "en", "html", posts_dir)}"\n',

        encoding="utf-8",

    )



    logger.info(

        "latest-digest include written: %s (+ %s)",

        include_path,

        data_path,

    )



    return include_path